export const FETCH_COINS_REQUEST = 'FETCH_COINS_REQUEST';
export const FETCH_COINS_SUCCESS = 'FETCH_COINS_SUCCESS';
export const FETCH_COINS_ERROR = 'FETCH_COINS_ERROR';
export const LAUNCH_LOGIN_USER = 'LAUNCH_LOGIN_USER';

export const FETCH_LOGIN_ERROR = 'FETCH_LOGIN_ERROR';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const FETCH_USER = 'FETCH_USER';


export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';


export const SAVE_LICENCE_REQUEST = 'SAVE_LICENCE_REQUEST';
export const SAVE_LICENCE_SUCCESS = 'SAVE_LICENCE_SUCCESS';
export const SAVE_LICENCE_ERROR = 'SAVE_LICENCE_ERROR';
export const FETCH_LICENCES_REQUEST = 'FETCH_LICENCES_REQUEST';
export const FETCH_LICENCES_SUCCESS = 'FETCH_LICENCES_SUCCESS';
export const FETCH_LICENCES_ERROR = 'FETCH_LICENCES_ERROR';
export const REQUEST_SHOW_MODAL = 'REQUEST_SHOW_MODAL';


export const FETCH_LICENCE_REQUEST = 'FETCH_LICENCE_REQUEST';
export const FETCH_LICENCE_SUCCESS = 'FETCH_LICENCE_SUCCESS';

export const UPDATE_LICENCE_REQUEST = 'UPDATE_LICENCE_REQUEST';
export const UPDATE_LICENCE_SUCCESS = 'UPDATE_LICENCE_SUCCESS';
export const UPDATE_LICENCE_ERROR = 'UPDATE_LICENCE_ERROR';